---
- name: Create the mongodb_exporter group
  group:
    name: "{{ _mongodb_exporter_system_group }}"
    state: present
    system: true
  when: _mongodb_exporter_system_group != "root"

- name: Cerate the mongodb_exporter user
  user:
    name: "{{ _mongodb_exporter_system_user }}"
    groups: "{{ _mongodb_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: _mongodb_exporter_system_user != "root"

- block:
    - name: Download mongodb_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/percona/mongodb_exporter/releases/download/v{{ mongodb_exporter_version }}/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ mongodb_exporter_checksum }}"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack mongodb_exporter binary
      become: false
      unarchive:
        src: "/tmp/mongodb_exporter-{{ mongodb_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/mongodb_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate mongodb_exporter binaries
      copy:
        src: "/tmp/mongodb_exporter"
        dest: "{{ _mongodb_exporter_binary_install_dir }}/mongodb_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart mongodb_exporter
      when: not ansible_check_mode
  when: mongodb_exporter_binary_local_dir | length == 0

- name: propagate locally distributed mongodb_exporter binary
  copy:
    src: "{{ mongodb_exporter_binary_local_dir }}/mongodb_exporter"
    dest: "{{ _mongodb_exporter_binary_install_dir }}/mongodb_exporter"
    mode: 0755
    owner: root
    group: root
  when: mongodb_exporter_binary_local_dir | length > 0
  notify: restart mongodb_exporter
