---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    mongodb_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in mongodb_exporter_web_listen_address"

- name: Check if mongodb_exporter is installed
  stat:
    path: "{{ _mongodb_exporter_binary_install_dir }}/mongodb_exporter"
  register: __mongodb_exporter_is_installed
  check_mode: false
  tags:
    - mongodb_exporter_install

- name: Gather currently installed mongodb_exporter version (if any)
  command: "{{ _mongodb_exporter_binary_install_dir }}/mongodb_exporter --version"
  args:
    warn: false
  changed_when: false
  register: __mongodb_exporter_current_version_output
  check_mode: false
  when: __mongodb_exporter_is_installed.stat.exists
  tags:
    - mongodb_exporter_install
    - skip_ansible_lint

- block:
    - name: Get checksum list from github
      set_fact:
        _checksums: "{{ lookup('url', 'https://github.com/percona/mongodb_exporter/releases/download/v' + mongodb_exporter_version + '/mongodb_exporter_' + mongodb_exporter_version + '_checksums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum for {{ go_arch }} architecture"
      set_fact:
        mongodb_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when:
        - "('linux-' + go_arch + '.tar.gz') in item"
  delegate_to: localhost
  when: mongodb_exporter_binary_local_dir | length == 0
