---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: geerlingguy/docker-centos8-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
  - name: bionic
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
